### ISSUE TITLE
Generating a .pb file for the trained model - Output Node Names

### ISSUE THREAD

**Issue by sk5100** [mahmoudmohsen213/airs#2]
I had followed your steps and trained/tested my model, and I was trying to create a .pb file from the multiple model files that are generated (the checkpoint files, .pbtxt graph, etc.) 

I have tried using freeze_graph.py, but I am unable to find the "output node name/s" that need to be input into the freeze_graph.py function. Do you know what the output nodes are for this trained model/graph?

**Comment by mahmoudmohsen213** [comment]
Honestly, no. Tensorflow takes the path of the generated files to initialise the model, so it handles saving and loading the model and initialising the weights and layers on it's own, and I didn't really dig into how it represents the model in the files. It's notable to say that the current versions of Tensorflow may have different APIs to save/load the models.
